'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CoinTracer.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neuere Version gefunden!{0}{0}Version {1}.{2}.{3} steht zum Download bereit.{0}{0}Soll nun die URL &apos;{4}&apos; im Standard-Browser geöffnet werden, damit Sie die Version herunterladen können? Der {5} schließt sich dadurch automatisch. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainCheckUpdates() As String
            Get
                Return ResourceManager.GetString("mainCheckUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beim Abrufen der Versionsinformationen ist ein Fehler aufgetreten: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainCheckUpdatesError() As String
            Get
                Return ResourceManager.GetString("mainCheckUpdatesError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ihre {0}-Version {1} ist noch aktuell! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainCheckUpdatesStillLatest() As String
            Get
                Return ResourceManager.GetString("mainCheckUpdatesStillLatest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Programmversion prüfen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainCheckUpdatesTitle() As String
            Get
                Return ResourceManager.GetString("mainCheckUpdatesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für {0} Tage wurden Kursinformationen hinzugefügt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainCoursesAddedMany() As String
            Get
                Return ResourceManager.GetString("mainCoursesAddedMany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es wurden keine Kursinformationen hinzugefügt, der Datenbestand war bereits aktuell. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainCoursesAddedNothing() As String
            Get
                Return ResourceManager.GetString("mainCoursesAddedNothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für einen Tag wurden neue Kursinformationen hinzugefügt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainCoursesAddedOne() As String
            Get
                Return ResourceManager.GetString("mainCoursesAddedOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Daten vorhanden bis: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainDataAvailableTo() As String
            Get
                Return ResourceManager.GetString("mainDataAvailableTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wenn Ihnen der {0} gefällt und Sie die Weiterentwicklung unterstützen möchten - ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainDonateAdvice() As String
            Get
                Return ResourceManager.GetString("mainDonateAdvice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sie haben Trade-Daten geändert. Um eventuelle Auswirkungen auf die Gewinnberechnung zu berücksichtigen werden jetzt alle berechneten Daten zurückgesetzt.{0}{0}Klicken Sie nur dann auf Abbrechen, wenn Sie sicher sind, dass die vorgenommenen Änderungen keine Auswirkungen auf den berechneten Gewinn/Verlust haben! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainEditTradesAdvice() As String
            Get
                Return ResourceManager.GetString("mainEditTradesAdvice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Geänderte Trade-Informationen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainEditTradesAdviceTitle() As String
            Get
                Return ResourceManager.GetString("mainEditTradesAdviceTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die (Zuletzt berechnet bis: {0}) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainGainingsLastCalculatedTo() As String
            Get
                Return ResourceManager.GetString("mainGainingsLastCalculatedTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plattformen ausblenden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainHidePlatforms() As String
            Get
                Return ResourceManager.GetString("mainHidePlatforms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Achtung! Diese Funktion löscht alle Daten inkl. der API-Zugangsdaten, sofern vorhanden, in der Datenbank unwiderruflich!{0}{0}Möchten Sie dies wirklich tun? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgDeleteDB1() As String
            Get
                Return ResourceManager.GetString("mainMsgDeleteDB1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Denken Sie bitte noch einmal darüber nach. Möchten Sie wirklich den gesamten Datenbestand unwiderruflich ausradieren?{0}{0}Möchten Sie wirklich forfahren? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgDeleteDB2() As String
            Get
                Return ResourceManager.GetString("mainMsgDeleteDB2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Allerletzte Rückfrage und gleichzeitig letzte Chance abzubrechen:{0}{0}Möchten Sie wirklich alle (!) Daten für immer und ewig löschen? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgDeleteDB3() As String
            Get
                Return ResourceManager.GetString("mainMsgDeleteDB3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erledigt, alle Daten gelöscht! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgDeleteDB4() As String
            Get
                Return ResourceManager.GetString("mainMsgDeleteDB4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datenbank löschen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgDeleteDBTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgDeleteDBTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erklärung/Disclaimer ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgDisclaimerTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgDisclaimerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für eine korrekte Gewinnberechnung fehlen noch Wechselkursinformationen. Sie können die Wechselkurse für USD im Reiter &apos;Übersicht&apos; unten rechts im Bereich &apos;{1}&apos; abrufen und die Gewinnermittlung anschließend neu starten.{0}{0}Möchten Sie die Wechselkursdaten jetzt automatisch abrufen? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGetCourses1() As String
            Get
                Return ResourceManager.GetString("mainMsgGetCourses1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wechselkursdaten liegen nur bis zum {0} vor, daher wird der Stichtag für die Gewinn-Verlust-Berechnung jetzt auf dieses Datum zurückgesetzt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGetCourses2() As String
            Get
                Return ResourceManager.GetString("mainMsgGetCourses2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für eine korrekte Gewinnberechnung fehlen noch Wechselkursinformationen (z. B. für dieses Datum: {0}). Bitte aktualisieren Sie erst die Wechselkurse für USD und starten Sie die Gewinnberechnung anschließend erneut. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGetCourses3() As String
            Get
                Return ResourceManager.GetString("mainMsgGetCourses3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kursdaten jetzt abrufen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGetCoursesBt1() As String
            Get
                Return ResourceManager.GetString("mainMsgGetCoursesBt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehlende Wechselkursinformationen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGetCoursesTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgGetCoursesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sie rufen die Währungskursdaten EUR &lt;&gt; USD zum ersten Mal ab. Es wird jetzt eine Verbindung mit www.bundesbank.de aufgebaut, um alle verfügbaren Kursdaten abzufragen.{0}{0}Bitte beachten Sie, dass das erste Auffüllen der Kurstabelle etwas Zeit in Anspruch nehmen kann. Sie können den Fortschritt beim Einlesen in der Statuszeile unten rechts verfolgen und während dessen mit dem Programm weiter arbeiten. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGetCoursesUSD() As String
            Get
                Return ResourceManager.GetString("mainMsgGetCoursesUSD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erster Kursdatenabruf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGetCoursesUSDTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgGetCoursesUSDTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufe Wechselkursdaten EUR &lt;&gt; US-Dollar ab... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGettingCoursesUSD() As String
            Get
                Return ResourceManager.GetString("mainMsgGettingCoursesUSD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gewinnberechnung abgeschlossen! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGotCourses() As String
            Get
                Return ResourceManager.GetString("mainMsgGotCourses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gewinne/Verluste berechnen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgGotCoursesTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgGotCoursesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Öffnen der Datenbank: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgLoadDBError() As String
            Get
                Return ResourceManager.GetString("mainMsgLoadDBError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CoinTracer-Datenbanken (*.data)|*.data|Alle Dateien (*.*)|*.* ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgLoadDBFilter() As String
            Get
                Return ResourceManager.GetString("mainMsgLoadDBFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup der aktuellen Datenbank erfolgreich geladen!{0}{0}Bitte beachten Sie, dass die zusätzlichen Angaben zum Bericht (Name, Steuernummer, Hinweis usw.) nicht in der Datenbank gespeichert sind und daher die bisherigen Einstellungen beibehalten wurden. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgLoadDBSuccess() As String
            Get
                Return ResourceManager.GetString("mainMsgLoadDBSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datenbank-Backup einlesen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgLoadDBSuccessTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgLoadDBSuccessTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnen einer CoinTracer-Datenbank ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgLoadDBTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgLoadDBTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Achtung: Alle aktuellen Daten werden durch Öffnen einer anderen Datenbank-Datei unwiederbringlich gelöscht!{0}{0}Klicken Sie auf OK, um fortzufahren, andernfalls auf Abbrechen. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgLoadDBWarning() As String
            Get
                Return ResourceManager.GetString("mainMsgLoadDBWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warnung vor Datenverlust ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgLoadDBWarningTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgLoadDBWarningTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Datenbank wurde erfolgreich reorganisiert und aufgeräumt, die Performance wurde optimiert! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgOptimizeDB1() As String
            Get
                Return ResourceManager.GetString("mainMsgOptimizeDB1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}{0}Die Datenbank-Datei wurde um {1}kB bereinigt. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgOptimizeDB2() As String
            Get
                Return ResourceManager.GetString("mainMsgOptimizeDB2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datenbank optimieren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgOptimizeDBTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgOptimizeDBTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für das Szenario &apos;{0}&apos; wurde noch keine Gewinn-Verlust-Berechnung durchgeführt.{0}{0}Wählen Sie im Reiter &apos;{1}&apos; bitte zuerst einen Stichtag und klicken dort auf die Schaltfläche &apos;{2}&apos;, um anschließend hier den Bericht laden zu können. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgReportReloadNoCalc() As String
            Get
                Return ResourceManager.GetString("mainMsgReportReloadNoCalc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Berichtsdaten vorhanden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgReportReloadNoCalcTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgReportReloadNoCalcTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Gewinn-/Verlust-Bericht wurde in die Zwischenablage kopiert. Sie können ihn nun weiterverarbeiten, z.B. in Microsoft Excel. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgReportToClipboard() As String
            Get
                Return ResourceManager.GetString("mainMsgReportToClipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bericht kopiert ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgReportToClipboardTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgReportToClipboardTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup der aktuellen Datenbank erfolgreich gespeichert! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgSaveDB2() As String
            Get
                Return ResourceManager.GetString("mainMsgSaveDB2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datenbank-Backup speichern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgSaveDB2Title() As String
            Get
                Return ResourceManager.GetString("mainMsgSaveDB2Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler beim Sichern der Datenbank: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgSaveDBError() As String
            Get
                Return ResourceManager.GetString("mainMsgSaveDBError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CoinTracer-Datenbanken (*.data)|*.data|Alle Dateien (*.*)|*.* ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgSaveDBFilter() As String
            Get
                Return ResourceManager.GetString("mainMsgSaveDBFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup der CoinTracer-Datenbank speichern unter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgSaveDBTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgSaveDBTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie zuerst aus, was importiert werden soll! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgSelectImportMethod() As String
            Get
                Return ResourceManager.GetString("mainMsgSelectImportMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Importmethode ausgewählt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgSelectImportMethodTitle() As String
            Get
                Return ResourceManager.GetString("mainMsgSelectImportMethodTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es gibt in den Trade-Daten noch Coin-Transfers, bei denen Herkunft- oder Zielplattform nicht bestimmt ist.{0}{0}Soll die Gewinn/-Verlustberechnung trotzdem durchgeführt werden? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgWarnUnclearTransfers() As String
            Get
                Return ResourceManager.GetString("mainMsgWarnUnclearTransfers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungeklärte Transfers ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainMsgWarnUnclearTransferstitle() As String
            Get
                Return ResourceManager.GetString("mainMsgWarnUnclearTransferstitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die - keine Daten vorhanden - ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainNoDataAvailable() As String
            Get
                Return ResourceManager.GetString("mainNoDataAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plattformen einblenden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainShowPlatforms() As String
            Get
                Return ResourceManager.GetString("mainShowPlatforms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wechselkurse aktualisieren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mainUpdateCoursesLabel() As String
            Get
                Return ResourceManager.GetString("mainUpdateCoursesLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Standard ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ScenarioDefault() As String
            Get
                Return ResourceManager.GetString("ScenarioDefault", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
